### PR TITLE
add new exercises

### PR DESCRIPTION
**Pull request by alirezatabatabaeian**

### CODE REVIEW

**Comment by alirezatabatabaeian** [comment]
Hi. Are the codes under review?

**Comment by alirezatabatabaeian** [comment]
??????

**Comment by ErikSchierboom** [comment]
Sorry for the delay, we were all on holidays. I'll have a look.

**Comment by ErikSchierboom** [comment]
Before I review, could you look at fixing the CI issues: https://github.com/exercism/func/actions/runs/7286216384/job/20085703711?pr=4?

**Pull request closed without merging**
